name: React Tests

on:
  push:
    branches:
      - main
      - production
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  react:
    uses: ./.github/workflows/test-suite.yml
    with:
      suite: react
